// <auto-generated />
using System;
using ExcelDoc.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelDoc.Server.Migrations
{
    [DbContext(typeof(ExcelDocDbContext))]
    [Migration("20260707182913_Tratamento_Documentos_Sucesso_E_Erro")]
    partial class Tratamento_Documentos_Sucesso_E_Erro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExcelDoc.Server.Models.Colecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FK_IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("NomeColecao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TipoColecao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdEmpresa")
                        .HasDatabaseName("IX_Colecoes_FK_IdEmpresa");

                    b.ToTable("Colecoes", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("FK_IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("LinkServiceLayer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SenhaSAP")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UsuarioSAP")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdEmpresa")
                        .IsUnique();

                    b.ToTable("Configuracoes", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("NomeDocumento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.DocumentoColecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FK_IdColecao")
                        .HasColumnType("int");

                    b.Property<int>("FK_IdDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdColecao")
                        .HasDatabaseName("IX_DocumentoColecao_FK_IdColecao");

                    b.HasIndex("FK_IdDocumento", "FK_IdColecao")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentoColecao_FK_IdDocumento_FK_IdColecao");

                    b.ToTable("DocumentoColecao", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Mapeamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<int>("FK_IdColecao")
                        .HasColumnType("int");

                    b.Property<int?>("FK_IdEmpresa")
                        .HasColumnType("int");

                    b.Property<bool>("IsPadrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdColecao")
                        .HasDatabaseName("IX_Mapeamento_FK_IdColecao");

                    b.HasIndex("FK_IdEmpresa")
                        .HasDatabaseName("IX_Mapeamento_FK_IdEmpresa");

                    b.ToTable("Mapeamento", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.MapeamentoCampo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescricaoCampo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("FK_IdMapeamento")
                        .HasColumnType("int");

                    b.Property<string>("Formato")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IndiceColuna")
                        .HasColumnType("int");

                    b.Property<string>("NomeCampo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TipoCampo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdMapeamento")
                        .HasDatabaseName("IX_MapeamentoCampos_FK_IdMapeamento");

                    b.HasIndex("FK_IdMapeamento", "IndiceColuna")
                        .IsUnique()
                        .HasDatabaseName("UX_MapeamentoCampos_FK_IdMapeamento_IndiceColuna");

                    b.ToTable("MapeamentoCampos", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.PerfilMapeamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<int>("FK_IdDocumento")
                        .HasColumnType("int");

                    b.Property<int?>("FK_IdEmpresa")
                        .HasColumnType("int");

                    b.Property<bool>("IsPadrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdDocumento")
                        .HasDatabaseName("IX_PerfilMapeamento_FK_IdDocumento");

                    b.HasIndex("FK_IdEmpresa")
                        .HasDatabaseName("IX_PerfilMapeamento_FK_IdEmpresa");

                    b.ToTable("PerfilMapeamento", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.PerfilMapeamentoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FK_IdColecao")
                        .HasColumnType("int");

                    b.Property<int>("FK_IdMapeamento")
                        .HasColumnType("int");

                    b.Property<int>("FK_IdPerfilMapeamento")
                        .HasColumnType("int");

                    b.Property<int?>("FK_IdPerfilMapeamentoItemPai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdColecao");

                    b.HasIndex("FK_IdMapeamento")
                        .HasDatabaseName("IX_PerfilMapeamentoItem_FK_IdMapeamento");

                    b.HasIndex("FK_IdPerfilMapeamentoItemPai")
                        .HasDatabaseName("IX_PerfilMapeamentoItem_FK_IdPerfilMapeamentoItemPai");

                    b.HasIndex("FK_IdPerfilMapeamento", "FK_IdColecao")
                        .IsUnique()
                        .HasDatabaseName("UX_PerfilMapeamentoItem_FK_IdPerfilMapeamento_FK_IdColecao");

                    b.ToTable("PerfilMapeamentoItem", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Processamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataExecucao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<int>("FK_IdDocumento")
                        .HasColumnType("int");

                    b.Property<int>("FK_IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("FK_IdPerfilMapeamento")
                        .HasColumnType("int");

                    b.Property<int>("FK_IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("HashArquivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TotalErro")
                        .HasColumnType("int");

                    b.Property<int>("TotalIgnorado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("int");

                    b.Property<int>("TotalSucesso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdDocumento");

                    b.HasIndex("FK_IdEmpresa");

                    b.HasIndex("FK_IdPerfilMapeamento");

                    b.HasIndex("FK_IdUsuario");

                    b.ToTable("Processamento", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.ProcessamentoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataExecucao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("Erro")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("FK_IdProcessamento")
                        .HasColumnType("int");

                    b.Property<string>("IdDocumentoUnico")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("IdExcel")
                        .HasColumnType("int");

                    b.Property<string>("JsonEnviado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JsonRetorno")
                        .HasColumnType("longtext");

                    b.Property<int>("LinhaExcel")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdProcessamento");

                    b.HasIndex("IdDocumentoUnico", "Status")
                        .HasDatabaseName("IX_ProcessamentoItem_IdDocumentoUnico_Status");

                    b.ToTable("ProcessamentoItem", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("FK_IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ResetPasswordCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ResetPasswordCodeExpiresAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("FK_IdEmpresa");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Colecao", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Empresa", "Empresa")
                        .WithMany("Colecoes")
                        .HasForeignKey("FK_IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Configuracao", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Empresa", "Empresa")
                        .WithOne("Configuracao")
                        .HasForeignKey("ExcelDoc.Server.Models.Configuracao", "FK_IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.DocumentoColecao", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Colecao", "Colecao")
                        .WithMany("DocumentoColecoes")
                        .HasForeignKey("FK_IdColecao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExcelDoc.Server.Models.Documento", "Documento")
                        .WithMany("DocumentoColecoes")
                        .HasForeignKey("FK_IdDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colecao");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Mapeamento", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Colecao", "Colecao")
                        .WithMany("Mapeamentos")
                        .HasForeignKey("FK_IdColecao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Mapeamento_Colecoes_FK_IdColecao");

                    b.HasOne("ExcelDoc.Server.Models.Empresa", "Empresa")
                        .WithMany("Mapeamentos")
                        .HasForeignKey("FK_IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Mapeamento_Empresa_FK_IdEmpresa");

                    b.Navigation("Colecao");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.MapeamentoCampo", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Mapeamento", "Mapeamento")
                        .WithMany("Campos")
                        .HasForeignKey("FK_IdMapeamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MapeamentoCampos_Mapeamento_FK_IdMapeamento");

                    b.Navigation("Mapeamento");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.PerfilMapeamento", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Documento", "Documento")
                        .WithMany("PerfilMapeamentos")
                        .HasForeignKey("FK_IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PerfilMapeamento_Documentos_FK_IdDocumento");

                    b.HasOne("ExcelDoc.Server.Models.Empresa", "Empresa")
                        .WithMany("PerfilMapeamentos")
                        .HasForeignKey("FK_IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PerfilMapeamento_Empresa_FK_IdEmpresa");

                    b.Navigation("Documento");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.PerfilMapeamentoItem", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Colecao", "Colecao")
                        .WithMany()
                        .HasForeignKey("FK_IdColecao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PerfilMapeamentoItem_Colecoes_FK_IdColecao");

                    b.HasOne("ExcelDoc.Server.Models.Mapeamento", "Mapeamento")
                        .WithMany()
                        .HasForeignKey("FK_IdMapeamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PerfilMapeamentoItem_Mapeamento_FK_IdMapeamento");

                    b.HasOne("ExcelDoc.Server.Models.PerfilMapeamento", "PerfilMapeamento")
                        .WithMany("Itens")
                        .HasForeignKey("FK_IdPerfilMapeamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PerfilMapeamentoItem_PerfilMapeamento_FK_IdPerfilMapeamento");

                    b.HasOne("ExcelDoc.Server.Models.PerfilMapeamentoItem", "ItemPai")
                        .WithMany("ItensFilhos")
                        .HasForeignKey("FK_IdPerfilMapeamentoItemPai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PerfilMapeamentoItem_PerfilMapeamentoItemPai");

                    b.Navigation("Colecao");

                    b.Navigation("ItemPai");

                    b.Navigation("Mapeamento");

                    b.Navigation("PerfilMapeamento");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Processamento", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Documento", "Documento")
                        .WithMany("Processamentos")
                        .HasForeignKey("FK_IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExcelDoc.Server.Models.Empresa", "Empresa")
                        .WithMany("Processamentos")
                        .HasForeignKey("FK_IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExcelDoc.Server.Models.PerfilMapeamento", "PerfilMapeamento")
                        .WithMany()
                        .HasForeignKey("FK_IdPerfilMapeamento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ExcelDoc.Server.Models.Usuario", "Usuario")
                        .WithMany("Processamentos")
                        .HasForeignKey("FK_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Empresa");

                    b.Navigation("PerfilMapeamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.ProcessamentoItem", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Processamento", "Processamento")
                        .WithMany("Itens")
                        .HasForeignKey("FK_IdProcessamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processamento");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Usuario", b =>
                {
                    b.HasOne("ExcelDoc.Server.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("FK_IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Colecao", b =>
                {
                    b.Navigation("DocumentoColecoes");

                    b.Navigation("Mapeamentos");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Documento", b =>
                {
                    b.Navigation("DocumentoColecoes");

                    b.Navigation("PerfilMapeamentos");

                    b.Navigation("Processamentos");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Empresa", b =>
                {
                    b.Navigation("Colecoes");

                    b.Navigation("Configuracao");

                    b.Navigation("Mapeamentos");

                    b.Navigation("PerfilMapeamentos");

                    b.Navigation("Processamentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Mapeamento", b =>
                {
                    b.Navigation("Campos");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.PerfilMapeamento", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.PerfilMapeamentoItem", b =>
                {
                    b.Navigation("ItensFilhos");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Processamento", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ExcelDoc.Server.Models.Usuario", b =>
                {
                    b.Navigation("Processamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
